export const data = {
  Singapore: {
    name: 'Model Tower',
    image: 'Model_Tower',
    building: 'Model_Tower',
    video: 'Model_Tower.mov',
    country: 'Singapore',
    city: 'Singapore',
    height: '1,517ft',
    floors: '99',
    function: 'Hotel',
  },
  Iceland: {
    name: 'Rainbow Arch',
    image: 'Rainbow',
    building: 'Rainbow',
    video: 'Rainbow.MOV',
    country: 'Iceland',
    city: 'Reykjavík',
    height: '310ft',
    floors: 'N/A',
    function: 'Sculpture',
  },
  London: {
    name: 'The Apex',
    image: 'Apex',
    building: 'Apex',
    video: 'Apex.mov',
    country: 'United Kingdom',
    city: 'London',
    height: '1,236ft',
    floors: '90',
    function: 'Residential',
  },
  Alaska: {
    name: 'Icebox',
    image: 'Icebox',
    building: 'Icebox',
    video: 'Icebox.mp4',
    country: 'U.S.A',
    city: 'Alaska',
    height: '602ft',
    floors: '12',
    function: 'Storage',
  },
  Chamonix: {
    name: 'Winter Cabin',
    video: 'Cabin.mov',
    image: 'Cabin',
    building: 'Cabin',
    country: 'France',
    city: 'Chamonix',
    height: '42ft',
    floors: '3',
    function: 'Residential',
  },
};
