export const data = {
  Dubai: {
    file: 'Rainbow.stl',
    name: 'Rainbow Tower',
    image: 'RAINBOW',
    country: 'U.A.E',
    city: 'Dubai',
    height: '500ft',
    floors: '45',
    function: 'Hotel',
    cameraPosition: 2,
    backgroundColor: '#fff',
    x: 0,
    y: -1.2,
    z: -2,
  },
  London: {
    file: 'Slice.stl',
    name: 'The Split',
    image: 'SPLIT',
    country: 'United Kingdom',
    city: 'London',
    height: '1,236ft',
    floors: '90',
    function: 'Residential',
    cameraPosition: 2,
    backgroundColor: '#fff',
    x: 0,
    y: -2.3,
    z: -1.7,
  },
  Cairo: {
    file: 'Pyramid.stl',
    name: 'The Great Pyramid',
    image: 'PYRAMID',
    country: 'Egypt',
    city: 'Cairo',
    height: '481ft',
    floors: '41',
    function: 'Hotel',
    cameraPosition: 2,
    backgroundColor: '#fff',
    x: 0,
    y: -1.2,
    z: -2.5,
  },
  Toronto: {
    file: 'Stacked.stl',
    name: 'Stacked Cube',
    image: 'STACK',
    country: 'Canada',
    city: 'Toronto',
    height: '602ft',
    floors: '65',
    function: 'Hotel',
    cameraPosition: 1,
    backgroundColor: '#fff',
    x: 0,
    y: -1.5,
    z: -2,
  },
  Sydney: {
    file: 'Ship.stl',
    name: 'The Bowl',
    image: 'SHIP',
    country: 'Australia',
    city: 'Sydney',
    height: '342ft',
    floors: '25',
    function: 'Residential',
    cameraPosition: 1,
    backgroundColor: '#fff',
    x: 0,
    y: -1.2,
    z: -2.2,
  },
  Singapore: {
    file: 'Jenga.stl',
    name: 'Model Tower',
    image: 'JENGA',
    country: 'Singapore',
    city: 'Singapore',
    height: '1,517ft',
    floors: '99',
    function: 'Hotel',
    cameraPosition: 2,
    backgroundColor: '#fff',
    x: 0,
    y: -2.8,
    z: -3,
  },
};
